AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CICD

  SAM Template for CICD

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  WebHookHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: ./dist/main.handler
      Runtime: nodejs14.x
      Architectures:
        - arm64
      Events:
        WebHookHandler:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: any
    # Layers:
    #   - !Ref NodeModulesFunctionLayer

  # NodeModulesFunctionLayer:  
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: CICD-node_modules
  #     Description: node_modules layer for CICD Lambda
  #     ContentUri: ./layer
  #     CompatibleRuntimes:
  #       - nodejs14.x
  #     LicenseInfo: ''
  #     RetentionPolicy: Retain


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for CICD function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  WebHookHandlerFunction:
    Description: "CICD Lambda Function ARN"
    Value: !GetAtt WebHookHandlerFunction.Arn
  WebHookHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for CICD function"
    Value: !GetAtt WebHookHandlerFunctionRole.Arn